import { redirect } from "next/navigation";
import { Plus, UserRound } from "lucide-react";
import type { User } from "@/generated/prisma/client";
import { UserRole } from "@/generated/prisma/enums";
import { disableUserAction, saveUserAction } from "@/actions/admin";
import { DriveTestButton } from "@/components/admin/drive-test-button";
import { Badge } from "@/components/ui/badge";
import { SubmitButton } from "@/components/ui/submit-button";
import { getCurrentUser } from "@/lib/auth/permissions";
import { prisma } from "@/lib/prisma";
import { ActionForm } from "@/components/ui/action-form";
import { ConfirmActionButton } from "@/components/ui/confirm-action-button";
import { ResetLinkButton } from "@/components/admin/reset-link-button";
import { roleLabel, tx, type Locale } from "@/lib/i18n";
import { getLocale } from "@/lib/i18n-server";

export const metadata = { title: "إدارة المستخدمين | User management" };
export default async function UsersPage() {
  const current = await getCurrentUser(); if (current.role !== UserRole.ADMIN) redirect("/admin");
  const locale = await getLocale();
  const users = await prisma.user.findMany({ include: { manager: true, _count: { select: { generatedContracts: true, directReports: true } } }, orderBy: { name: "asc" } });
  const managers = users.filter(u => u.role === UserRole.ADMIN || u.role === UserRole.SUPERVISOR);
  return <div className="space-y-6"><div><p className="mb-1 text-sm font-bold text-[var(--primary)]">{tx(locale, "صلاحيات ومجلدات", "Permissions and folders")}</p><h1 className="text-2xl font-black">{tx(locale, "إدارة المستخدمين", "User management")}</h1><p className="mt-2 text-sm text-[var(--muted)]">{tx(locale, "لكل مستخدم مجلد Google Drive مستقل تحفظ داخله نسخ عقوده وملفات PDF الموثقة.", "Each user has a dedicated Google Drive folder for contract copies and certified PDFs.")}</p></div><details className="card p-5"><summary className="flex cursor-pointer list-none items-center gap-2 font-black"><Plus className="size-5 text-[var(--primary)]" />{tx(locale, "إضافة مستخدم", "Add user")}</summary><UserForm managers={managers} locale={locale} /></details><section className="space-y-3">{users.map(user => <details className="card p-5" key={user.id}><summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--surface-muted)]"><UserRound className="size-4" /></span><div><p className="font-black">{user.name}</p><p className="mt-1 text-xs text-[var(--muted)]" dir="ltr">{user.email}</p></div></div><div className="flex flex-wrap items-center gap-2"><Badge tone="info">{roleLabel(locale, user.role)}</Badge><Badge tone={user.isActive ? "success" : "danger"}>{user.isActive ? tx(locale, "فعال", "Active") : tx(locale, "معطل", "Disabled")}</Badge><span className="text-xs text-[var(--muted)]">{user._count.generatedContracts} {tx(locale, "عقد", "contracts")}</span>{user.googleFolderId && <DriveTestButton id={user.googleFolderId} type="folder" />}</div></summary><div className="mt-5 flex flex-wrap justify-end gap-2"><ResetLinkButton userId={user.id} />{user.id !== current.id && user.isActive && <ConfirmActionButton action={disableUserAction} id={user.id} title={tx(locale, "تعطيل هذا المستخدم؟", "Disable this user?")} description={tx(locale, "سيتم منعه من الدخول فورًا مع الاحتفاظ بعقوده وسجل العمليات.", "Access will be revoked immediately while contracts and audit history remain.")} successMessage={tx(locale, "تم تعطيل المستخدم.", "User disabled.")} label={tx(locale, "تعطيل", "Disable")} />}</div><UserForm user={user} managers={managers} locale={locale} /></details>)}</section></div>;
}
function UserForm({ user, managers, locale }: { user?: User; managers: User[]; locale: Locale }) { return <ActionForm action={saveUserAction} successMessage={tx(locale, user ? "تم حفظ تعديلات المستخدم." : "تمت إضافة المستخدم بنجاح.", user ? "User changes saved." : "User added successfully.")} className="mt-5 grid gap-4 border-t pt-5 md:grid-cols-2">{user && <input type="hidden" name="id" value={user.id} />}<label><span className="label">{tx(locale, "الاسم", "Name")}</span><input className="field" name="name" defaultValue={user?.name} required /></label><label><span className="label">{tx(locale, "البريد", "Email")}</span><input className="field" name="email" type="email" defaultValue={user?.email} required dir="ltr" /></label><label><span className="label">{tx(locale, "كلمة المرور", "Password")} {user && <span className="font-normal text-[var(--muted)]">({tx(locale, "اتركها فارغة دون تغيير", "leave blank to keep unchanged")})</span>}</span><input className="field" name="password" type="password" minLength={8} required={!user} autoComplete="new-password" dir="ltr" /></label><label><span className="label">{tx(locale, "الدور", "Role")}</span><select className="field" name="role" defaultValue={user?.role || UserRole.CONTRACT_EMPLOYEE}>{Object.values(UserRole).map(role => <option key={role} value={role}>{roleLabel(locale, role)}</option>)}</select></label><label><span className="label">Google Drive Folder ID</span><input className="field" name="googleFolderId" defaultValue={user?.googleFolderId || ""} dir="ltr" /></label><label><span className="label">{tx(locale, "المدير المباشر", "Direct manager")}</span><select className="field" name="managerId" defaultValue={user?.managerId || ""}><option value="">{tx(locale, "بدون", "None")}</option>{managers.filter(m => m.id !== user?.id).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label><span className="label">{tx(locale, "القسم", "Department")}</span><input className="field" name="department" defaultValue={user?.department || ""} /></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="isActive" defaultChecked={user?.isActive ?? true} />{tx(locale, "فعال", "Active")}</label><div className="md:col-span-2 md:text-left"><SubmitButton label={tx(locale, "حفظ", "Save")} /></div></ActionForm>; }
