import Link from "next/link";
import { ExternalLink, FileText, Plus } from "lucide-react";
import type { Agency, ContractTemplate, Package } from "@/generated/prisma/client";
import { UserRole } from "@/generated/prisma/enums";
import { archiveTemplateAction, saveTemplateAction } from "@/actions/admin";
import { DriveTestButton, TestCopyButton } from "@/components/admin/drive-test-button";
import { Badge } from "@/components/ui/badge";
import { SubmitButton } from "@/components/ui/submit-button";
import { getCurrentUser } from "@/lib/auth/permissions";
import { prisma } from "@/lib/prisma";
import { formatDateTime, formatMoney } from "@/lib/utils";
import { ActionForm } from "@/components/ui/action-form";
import { ConfirmActionButton } from "@/components/ui/confirm-action-button";
import { tx } from "@/lib/i18n";
import { getLocale } from "@/lib/i18n-server";

export const metadata = { title: "إدارة القوالب" };

export default async function TemplatesPage() {
  const user = await getCurrentUser();
  const locale = await getLocale();
  const [templates, agencies, packages] = await Promise.all([
    prisma.contractTemplate.findMany({ include: { agency: true, package: true, _count: { select: { generatedContracts: true } } }, orderBy: [{ agency: { name: "asc" } }, { package: { name: "asc" } }, { version: "desc" }] }),
    prisma.agency.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.package.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
  ]);
  return <div className="space-y-6"><div><p className="mb-1 text-sm font-bold text-[var(--primary)]">{tx(locale, "File ID هو مصدر الربط", "File ID is the source of truth")}</p><h1 className="text-2xl font-black">{tx(locale, "إدارة قوالب العقود", "Contract templates")}</h1><p className="mt-2 text-sm text-[var(--muted)]">{tx(locale, "الإصدار القديم يبقى محفوظًا، والعقود القديمة لا تتغير عند إضافة إصدار أحدث.", "Older versions remain preserved and existing contracts never change when a new version is added.")}</p></div>
    <details className="card p-5"><summary className="flex cursor-pointer list-none items-center gap-2 font-black"><Plus className="size-5 text-[var(--primary)]" />{tx(locale, "إضافة إصدار قالب", "Add template version")}</summary><TemplateForm agencies={agencies} packages={packages} locale={locale} /></details>
    <section className="space-y-3">{templates.map(template => <details className="card p-5" key={template.id}><summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[var(--surface-muted)]"><FileText className="size-4" /></span><div className="min-w-0"><p className="truncate font-black">{template.templateName}</p><p className="mt-1 text-xs text-[var(--muted)]">{template.agency.nameAr || template.agency.name} · {template.package.name} · v{template.version} · {template._count.generatedContracts} {tx(locale, "عقد", "contracts")}</p></div></div><div className="flex flex-wrap items-center gap-2"><Badge tone={template.isActive ? "success" : "danger"}>{template.isActive ? tx(locale, "فعال", "Active") : tx(locale, "معطل", "Disabled")}</Badge><Badge tone={template.healthStatus === "HEALTHY" ? "success" : template.healthStatus === "UNKNOWN" ? "neutral" : "danger"}>{template.healthStatus}</Badge></div></summary>
      <div className="mt-5 border-t pt-5"><div className="mb-4 grid gap-3 rounded-xl bg-[var(--surface-muted)] p-4 text-sm md:grid-cols-4"><div><p className="text-xs text-[var(--muted)]">{tx(locale, "النوع / المدة", "Type / duration")}</p><p className="mt-1 font-bold">{template.contractType} · {template.duration ?? "—"} {tx(locale, "شهر", "months")}</p></div><div><p className="text-xs text-[var(--muted)]">{tx(locale, "السعر / العرض", "Price / offer")}</p><p className="mt-1 font-bold">{formatMoney(template.price?.toString() ?? null, template.currency)} · {template.offerCode || tx(locale, "بدون", "None")}</p></div><div><p className="text-xs text-[var(--muted)]">{tx(locale, "السريان", "Effective period")}</p><p className="mt-1 font-bold">{template.effectiveFrom.toISOString().slice(0,10)} — {template.effectiveTo?.toISOString().slice(0,10) || tx(locale, "مفتوح", "Open")}</p></div><div><p className="text-xs text-[var(--muted)]">{tx(locale, "آخر فحص", "Last check")}</p><p className="mt-1 font-bold">{template.lastHealthCheckedAt ? formatDateTime(template.lastHealthCheckedAt) : tx(locale, "لم يُفحص", "Not checked")}</p></div></div>
        <div className="mb-5 flex flex-wrap gap-2"><DriveTestButton id={template.googleFileId} templateId={template.id} /><Link href={template.googleFileUrl || `https://docs.google.com/document/d/${template.googleFileId}/edit`} target="_blank" className="inline-flex min-h-9 items-center gap-2 rounded-xl border bg-[var(--surface)] px-3 text-xs font-bold hover:bg-[var(--surface-muted)]">{tx(locale, "فتح القالب", "Open template")} <ExternalLink className="size-3" /></Link>{user.role === UserRole.ADMIN && <TestCopyButton templateId={template.id} />}</div>
        <div className="mb-4 flex justify-end"><ConfirmActionButton action={archiveTemplateAction} id={template.id} title={tx(locale, "حذف هذا القالب؟", "Delete this template?")} description={tx(locale, "سيتم إيقافه وإخفاؤه من إنشاء العقود مع الاحتفاظ بالعقود القديمة.", "It will be disabled and hidden from contract creation while old contracts remain intact.")} successMessage={tx(locale, "تم حذف القالب.", "Template deleted.")} /></div>
        <TemplateForm template={template} agencies={agencies} packages={packages} locale={locale} />
      </div>
    </details>)}</section>
  </div>;
}

type TemplateWithRelations = ContractTemplate & { agency?: Agency; package?: Package };
function TemplateForm({ template, agencies, packages, locale }: { template?: TemplateWithRelations; agencies: Agency[]; packages: Package[]; locale: "ar" | "en" }) {
  return <ActionForm action={saveTemplateAction} successMessage={tx(locale, template ? "تم حفظ تعديلات القالب." : "تمت إضافة القالب بنجاح.", template ? "Template changes saved." : "Template added successfully.")} className="mt-5 grid gap-4 border-t pt-5 md:grid-cols-2 xl:grid-cols-4">{template && <input type="hidden" name="id" value={template.id} />}
    <label className="xl:col-span-2"><span className="label">{tx(locale, "اسم القالب", "Template name")}</span><input className="field" name="templateName" defaultValue={template?.templateName} required /></label><label><span className="label">{tx(locale, "كود القالب", "Template code")}</span><input className="field" name="templateCode" defaultValue={template?.templateCode} required dir="ltr" /></label><label><span className="label">{tx(locale, "الإصدار", "Version")}</span><input className="field" name="version" defaultValue={template?.version || "1.0"} required dir="ltr" /></label>
    <label><span className="label">{tx(locale, "الشركة", "Company")}</span><select className="field" name="agencyId" defaultValue={template?.agencyId} required><option value="">{tx(locale, "اختر", "Choose")}</option>{agencies.map(a => <option key={a.id} value={a.id}>{a.nameAr || a.name}</option>)}</select></label><label><span className="label">{tx(locale, "الباقة", "Package")}</span><select className="field" name="packageId" defaultValue={template?.packageId} required><option value="">{tx(locale, "اختر", "Choose")}</option>{packages.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span className="label">{tx(locale, "نوع العقد", "Contract type")}</span><input className="field" name="contractType" defaultValue={template?.contractType || "Marketing"} required /></label><label><span className="label">{tx(locale, "المدة (شهر)", "Duration (months)")}</span><input className="field" name="duration" type="number" min="1" defaultValue={template?.duration ?? ""} /></label>
    <label className="md:col-span-2 xl:col-span-3"><span className="label">{tx(locale, "رابط Google Docs أو File ID", "Google Docs URL or File ID")}</span><input className="field" name="googleFileInput" defaultValue={template?.googleFileUrl || template?.googleFileId} required dir="ltr" /></label><label><span className="label">{tx(locale, "العملة", "Currency")}</span><input className="field" name="currency" defaultValue={template?.currency || "SAR"} maxLength={3} required dir="ltr" /></label>
    <label><span className="label">{tx(locale, "السعر", "Price")}</span><input className="field" name="price" type="number" step="0.01" min="0" defaultValue={template?.price?.toString() ?? ""} /></label><label><span className="label">{tx(locale, "كود العرض", "Offer code")}</span><input className="field" name="offerCode" defaultValue={template?.offerCode || ""} dir="ltr" /></label><label><span className="label">{tx(locale, "بداية السريان", "Effective from")}</span><input className="field" name="effectiveFrom" type="date" defaultValue={template?.effectiveFrom.toISOString().slice(0,10) || new Date().toISOString().slice(0,10)} required /></label><label><span className="label">{tx(locale, "نهاية السريان", "Effective to")}</span><input className="field" name="effectiveTo" type="date" defaultValue={template?.effectiveTo?.toISOString().slice(0,10) || ""} /></label>
    <label className="md:col-span-2 xl:col-span-4"><span className="label">{tx(locale, "ملاحظات", "Notes")}</span><textarea className="field min-h-20" name="notes" defaultValue={template?.notes || ""} /></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="isActive" defaultChecked={template?.isActive ?? true} />{tx(locale, "فعال", "Active")}</label><div className="md:col-span-2 md:text-left"><SubmitButton label={tx(locale, template ? "حفظ التعديلات" : "إضافة القالب", template ? "Save changes" : "Add template")} /></div>
  </ActionForm>;
}
