import { FileClock, Search } from "lucide-react";
import { UserRole } from "@/generated/prisma/enums";
import { getCurrentUser } from "@/lib/auth/permissions";
import { prisma } from "@/lib/prisma";
import { formatDateTime } from "@/lib/utils";
import { tx } from "@/lib/i18n";
import { getLocale } from "@/lib/i18n-server";

export const metadata = { title: "سجل التدقيق | Audit log" };
export default async function AuditPage({ searchParams }: { searchParams: Promise<{ q?: string; action?: string }> }) {
  const params = await searchParams; const user = await getCurrentUser();
  const locale = await getLocale();
  const scope = user.role === UserRole.ADMIN ? {} : { OR: [{ userId: user.id }, { user: { managerId: user.id } }] };
  const logs = await prisma.auditLog.findMany({ where: { AND: [scope, params.q ? { OR: [{ entityId: { contains: params.q, mode: "insensitive" } }, { requestId: { contains: params.q, mode: "insensitive" } }, { user: { name: { contains: params.q, mode: "insensitive" } } }] } : {}, params.action ? { action: { contains: params.action, mode: "insensitive" } } : {}] }, include: { user: true }, orderBy: { createdAt: "desc" }, take: 300 });
  return <div className="space-y-6"><div><p className="mb-1 text-sm font-bold text-[var(--primary)]">{tx(locale, "أثر كامل للعمليات", "Complete activity trail")}</p><h1 className="text-2xl font-black">{tx(locale, "سجل التدقيق", "Audit log")}</h1><p className="mt-2 text-sm text-[var(--muted)]">{tx(locale, "السجل للقراءة فقط ولا يعرض بيانات دخول أو رموز وصول.", "This read-only log never exposes credentials or access tokens.")}</p></div><form className="card flex flex-col gap-3 p-4 sm:flex-row"><input className="field" name="q" defaultValue={params.q} placeholder={tx(locale, "Request ID، مستخدم أو Entity ID", "Request ID, user, or entity ID")} /><input className="field" name="action" defaultValue={params.action} placeholder={tx(locale, "نوع العملية", "Action type")} /><button className="min-h-11 rounded-xl bg-[var(--primary)] px-5 font-bold text-white" aria-label={tx(locale, "بحث في السجل", "Search audit log")}><Search className="mx-auto size-4" /></button></form><section className="card overflow-hidden">{logs.length === 0 ? <div className="p-14 text-center"><FileClock className="mx-auto mb-3 size-10 text-[var(--muted)]" /><p className="font-black">{tx(locale, "لا توجد سجلات مطابقة", "No matching log entries")}</p></div> : <div className="table-wrap"><table className="data-table"><thead><tr><th>{tx(locale, "التاريخ", "Date")}</th><th>{tx(locale, "المستخدم", "User")}</th><th>{tx(locale, "العملية", "Action")}</th><th>{tx(locale, "الكيان", "Entity")}</th><th>Request ID</th><th>{tx(locale, "التفاصيل", "Details")}</th></tr></thead><tbody>{logs.map(log => <tr key={log.id}><td className="whitespace-nowrap text-xs">{formatDateTime(log.createdAt, locale)}</td><td>{log.user?.name || tx(locale, "النظام", "System")}</td><td className="font-bold" dir="ltr">{log.action}</td><td><p dir="ltr">{log.entityType}</p><p className="max-w-36 truncate text-xs text-[var(--muted)]" dir="ltr">{log.entityId || "—"}</p></td><td className="max-w-36 truncate text-xs" dir="ltr">{log.requestId || "—"}</td><td><details><summary className="cursor-pointer text-xs font-bold text-[var(--primary)]">{tx(locale, "عرض", "View")}</summary><pre className="mt-2 max-w-md overflow-auto rounded-lg bg-[var(--surface-muted)] p-3 text-[11px]" dir="ltr">{JSON.stringify(log.details, null, 2)}</pre></details></td></tr>)}</tbody></table></div>}</section></div>;
}
