import { redirect } from "next/navigation";
import { PackageOpen, Plus } from "lucide-react";
import { UserRole } from "@/generated/prisma/enums";
import { archivePackageAction, savePackageAction } from "@/actions/admin";
import { Badge } from "@/components/ui/badge";
import { SubmitButton } from "@/components/ui/submit-button";
import { getCurrentUser } from "@/lib/auth/permissions";
import { prisma } from "@/lib/prisma";
import { formatMoney } from "@/lib/utils";
import { ActionForm } from "@/components/ui/action-form";
import { ConfirmActionButton } from "@/components/ui/confirm-action-button";
import { tx, type Locale } from "@/lib/i18n";
import { getLocale } from "@/lib/i18n-server";

export const metadata = { title: "إدارة الباقات | Package management" };
export default async function PackagesPage() {
  const user = await getCurrentUser(); if (user.role !== UserRole.ADMIN) redirect("/admin");
  const locale = await getLocale();
  const packages = await prisma.package.findMany({ include: { _count: { select: { templates: true, generatedContracts: true } } }, orderBy: [{ category: "asc" }, { name: "asc" }] });
  return <div className="space-y-6"><div><p className="mb-1 text-sm font-bold text-[var(--primary)]">{tx(locale, "تعريف موحد", "Standard catalog")}</p><h1 className="text-2xl font-black">{tx(locale, "إدارة الباقات", "Package management")}</h1></div><details className="card p-5" open><summary className="flex cursor-pointer list-none items-center gap-2 font-black"><Plus className="size-5 text-[var(--primary)]" />{tx(locale, "إضافة باقة", "Add package")}</summary><PackageForm locale={locale} /></details><section className="space-y-3">{packages.map(item => <details className="card p-5" key={item.id}><summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--surface-muted)]"><PackageOpen className="size-4" /></span><div><p className="font-black">{item.name} <span className="text-xs text-[var(--muted)]">({item.code})</span></p><p className="mt-1 text-xs text-[var(--muted)]">{item.category} · {item.defaultDuration ?? "—"} {tx(locale, "شهر", "months")} · {formatMoney(item.defaultPrice?.toString() ?? null, item.currency, locale)}</p></div></div><Badge tone={item.isActive ? "success" : "danger"}>{item.isActive ? tx(locale, "فعالة", "Active") : tx(locale, "معطلة", "Disabled")}</Badge></summary><div className="mt-5 flex justify-end"><ConfirmActionButton action={archivePackageAction} id={item.id} title={tx(locale, "حذف هذه الباقة؟", "Delete this package?")} description={tx(locale, "سيتم إيقافها وإخفاؤها من إنشاء العقود مع الاحتفاظ بالسجلات القديمة.", "It will be disabled and hidden from contract creation while historical records remain.")} successMessage={tx(locale, "تم حذف الباقة.", "Package deleted.")} /></div><PackageForm item={item} locale={locale} /></details>)}</section></div>;
}
function PackageForm({ item, locale }: { item?: { id: string; name: string; code: string; category: string; description: string | null; defaultDuration: number | null; defaultPrice: { toString(): string } | null; currency: string; isActive: boolean }; locale: Locale }) { return <ActionForm action={savePackageAction} successMessage={tx(locale, item ? "تم حفظ تعديلات الباقة." : "تمت إضافة الباقة بنجاح.", item ? "Package changes saved." : "Package added successfully.")} className="mt-5 grid gap-4 border-t pt-5 md:grid-cols-2">{item && <input type="hidden" name="id" value={item.id} />}<label><span className="label">{tx(locale, "اسم الباقة", "Package name")}</span><input className="field" name="name" defaultValue={item?.name} required /></label><label><span className="label">{tx(locale, "الكود", "Code")}</span><input className="field" name="code" defaultValue={item?.code} required dir="ltr" /></label><label><span className="label">{tx(locale, "الفئة", "Category")}</span><input className="field" name="category" defaultValue={item?.category} placeholder="VIP / SEO / Individual" required /></label><label><span className="label">{tx(locale, "المدة الافتراضية بالشهور", "Default duration in months")}</span><input className="field" name="defaultDuration" type="number" min="1" defaultValue={item?.defaultDuration ?? ""} /></label><label><span className="label">{tx(locale, "السعر الافتراضي", "Default price")}</span><input className="field" name="defaultPrice" type="number" min="0" step="0.01" defaultValue={item?.defaultPrice?.toString() ?? ""} /></label><label><span className="label">{tx(locale, "العملة", "Currency")}</span><input className="field" name="currency" defaultValue={item?.currency || "SAR"} maxLength={3} required dir="ltr" /></label><label className="md:col-span-2"><span className="label">{tx(locale, "الوصف", "Description")}</span><textarea className="field min-h-20" name="description" defaultValue={item?.description || ""} /></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="isActive" defaultChecked={item?.isActive ?? true} />{tx(locale, "فعالة", "Active")}</label><div className="md:text-left"><SubmitButton label={tx(locale, "حفظ", "Save")} /></div></ActionForm>; }
